### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by wellcaffeinated** [keeganlow/SimpleSimplex#1]
Hi there
I just want to use this code. But there is no license or copywrite information. Presumably you intend this to be open source, but I would just like to know if you've licensed it MIT/GPL... or what. Thanks!

**Comment by keeganlow** [comment]
Thanks for your interest. This code is MIT licensed. 

Just out of curiosity, how are you planning to use this code?

**Comment by wellcaffeinated** [comment]
It will be used for science :)
Specifically calculations in quantum mechanics.
